repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
        files: ^(src/.*\.py|test/.*\.py)$
      - id: check-merge-conflict
        files: ^(src/.*\.py|test/.*\.py)$
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        files: ^(src/.*\.py|test/.*\.py)$
      - id: trailing-whitespace
        files: ^(src/.*\.py|test/.*\.py)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.2"
    hooks:
      - id: ruff
        files: ^(src/.*\.py|test/.*\.py)$
        args: [--exit-non-zero-on-fix]
      - id: ruff-format
        files: ^(src/.*\.py|test/.*\.py)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        entry: hadolint
        language: system
        types: [dockerfile]
        files: ^docker/.*/Dockerfile$
        args: ["--ignore", "DL3013", "--ignore", "DL3042"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        args: ["--short-report", "--ignore=70612"]
        files: pyproject.toml

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
