site_name: hvh-backend
repo_url: https://github.com/mesteriis/hvh-backend
site_url: https://mesteriis.github.io/hvh-backend
site_description: Home Video Hub
site_author: Aleksander Meshchryakov
edit_uri: edit/main/docs/
repo_name: mesteriis/hvh-backend
copyright: Maintained by <a href="https://mesteriis.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mesteriis/hvh-backend
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hvh-backend

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
