#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


export DB_NAME="paragraf"
export DIR_PATH="/migrations"


echo "Starting the main database creation script..."
# Создание базы данных с использованием SQL-файла. Результат выводится в /dev/null для подавления вывода.
psql -a -q -f $DIR_PATH/$DB_NAME.sql >> /dev/null

# Функция для выполнения всех SQL-скриптов в указанной директории.
execute_sql_scripts() {
    local dir=$1
    echo "Starting the SQL scripts in directory $dir..."
    for file in `find $dir -type f -name "*.sql" | sort`
    do
        echo "Executing SQL script $file..."
        # Выполнение каждого SQL-скрипта. Результат выводится в /dev/null для подавления вывода.
        psql -d $DB_NAME -a -q -f $file >> /dev/null
    done
    echo "Execution of SQL scripts in directory $dir... DONE"
}

# Вызов функции execute_sql_scripts для каждой директории, содержащей SQL-скрипты.
# execute_sql_scripts $DIR_PATH/sql_scripts_archive
execute_sql_scripts $DIR_PATH/sql_scripts_upd_before
execute_sql_scripts $DIR_PATH/sql_scripts_upd_beyond

echo "Database creation ended"
